### ISSUE TITLE
Seems like buffer slider is a good candidate for observables

### ISSUE THREAD

**Issue by tomwayson** [jwasilgeo/angular2-esri-playground#1]
Seems like the slider change events can be treated as a stream and would be a good demo of how to use observables to debounce expensive operations.

See http://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html

**Comment by jwasilgeo** [comment]
super cursory and early draft, but feel free to peruse:

https://github.com/jwasilgeo/angular2-esri-playground/blob/observable-input-slider/app/geometry-engine-showcase.component.ts
