### ISSUE TITLE
Question on "click"event of "MapView" class

### ISSUE THREAD

**Issue by Shawn-Fan** [jwasilgeo/angular2-esri-playground#12]
I try to follow the way of "angular2-esri-playground" by adding the following example in the project:
   https://developers.arcgis.com/javascript/latest/sample-code/watch-for-changes/index.html
everything works fine, map shows up, no error message. When I click on the map, popup windows show up, but the following code: 

``` javascript
view.on("click", function(evt) {
  var info = "</br><span> view click event: </span> x: " + evt.mapPoint.x.toFixed(2) + " y: " + evt.mapPoint.y.toFixed(2);
  //displayMessage(info);
  console.log(info);
});
```

doesn't work. 
Thanks in advance.

**Comment by jwasilgeo** [comment]
Can you provide more info please?  Where did you try to put this code? Does anything appear at all in the `evt` object if the click listener is even firing?

**Comment by Shawn-Fan** [comment]
I followed the structure of your project, several files changed.

1). geometry-engine-showcase.component.ts
1. import { Component, ViewChildren } from '@angular/core';
2. import { EsriMapViewComponent } from './esri-map-view.component';
3. 
4. @Component({
5.     selector: 'geometry-engine-showcase',
6.     template:
7.         `
8.         <h4>Example</h4>
9. 
10.         <esri-map-view
11.             zoom="12" centerLng="-120.66" centerLat="35.475" rotation="0">
12.         </esri-map-view>
13.         `,
14.     directives: [EsriMapViewComponent]
15. })
16. export class GeometryEngineShowcaseComponent { 
17. }

2). esri-map-view.component.ts
1. import { Component, ElementRef, Input, Output, EventEmitter } from '@angular/core';
2. import { AnalysisMapService1 } from './map.service';
3. import Map from 'esri/Map';
4. import MapView from 'esri/views/MapView';
5. 
6. @Component({
7.     selector: 'esri-map-view',
8.     template: '<div></div>',
9.     providers: [AnalysisMapService1]
10. })
11. export class EsriMapViewComponent {
12.     @Input() zoom: number;
13.     @Input() centerLng: number;
14.     @Input() centerLat: number;
15.     @Input() rotation: number;
16. 
17.     //@Output() viewCreated = new EventEmitter();
18. 
19.     view: any = null;
20. 
21.     constructor(
22.         private _mapService: AnalysisMapService1,
23.         private elRef: ElementRef
24.     ) {}
25. 
26.     ngOnInit() {
27.         this.view = new MapView({
28.             container: this.elRef.nativeElement.firstChild,
29.             map: this._mapService.map,
30.             zoom: this.zoom,
31.             center: [this.centerLng, this.centerLat],
32.             rotation: this.rotation
33.         });
34.     }
35. }

3).map.service.ts
1. import { Injectable } from '@angular/core';
2. import Map from 'esri/Map';
3. 
4. import WebMap from 'esri/WebMap';
5. import MapView from 'esri/views/MapView';
6. 
7. @Injectable()
8. export class AnalysisMapService1 {
9.     map: any = null;
10.     view: any = null;
11.     webmap: any = null;
12.     constructor() {
13.         this.webmap = new WebMap({
14.             portalItem:{id:"974c6641665a42bf8a57da08e607bb6f"}
15.         });
16.         this.view = new MapView({
17.             map: this.webmap
18.         });
19.         this.view.on("click", function(evt){
20.               var info = "</br><span> view click event: </span> x: " + evt.mapPoint.x.toFixed(2) + " y: " + evt.mapPoint.y.toFixed(2);
21.               //displayMessage(info);
22.               console.log(info);
23.         });
24. 
25.         this.map = this.view.map;
26.     }
27. }

**Comment by jwasilgeo** [comment]
@Shawn-Fan I'm unsure why it isn't working for you, and I am having a difficult time following the unformatted JS code.

If I put a click listener [here in the code](https://github.com/jwasilgeo/angular2-esri-playground/blob/master/app/esri-map-view.component.ts#L34), it works as expected.

``` javascript
this.view.on('click', function(evt) {
    var info = "</br><span> view click event: </span> x: " + evt.mapPoint.x.toFixed(2) + " y: " + evt.mapPoint.y.toFixed(2);
    console.log(info);
});
```

**Comment by Shawn-Fan** [comment]
It works now, thanks for your info very much. I am wondering if the reason is the event can not be attached to MapView object before the MapView in the Map(before map showing up)?

**Comment by jwasilgeo** [comment]
Hi @Shawn-Fan, sorry for the delay.  Are you still experiencing any issues with this?

**Comment by Shawn-Fan** [comment]
Thanks, @jwasilgeo , It looks like you updated the project to Angular 2 . I solved the problem by adding static property to it.
