### ISSUE TITLE
Router with #

### ISSUE THREAD

**Issue by jwasilgeo** [jwasilgeo/angular2-esri-playground#3]
Get router working properly, esp. with gh-pages. Might need to use `#`.

**Comment by jwasilgeo** [comment]
@tomwayson if you're curious what I brute force came up with so far, this'll work locally: https://github.com/jwasilgeo/angular2-esri-playground/commit/cd37c1fece82eeacf0a4168ede0e9eb815ae5b7a

Just spent some time with these changes over on `gh-pages` with no luck, with Angular warnings that I still need a base href and what not.  However, experimenting with a few different base href values didn't help either on `gh-pages`.  For now, this is just on `master`, and `gh-pages` is back to how it was with the original location strategy (and will thus break on route browser refresh).

**Comment by tomwayson** [comment]
:frowning:

**Comment by jwasilgeo** [comment]
Doesn't seem to be a problem anymore with the latest router w/ Angular2 release.
